import org.apache.tools.ant.filters.ReplaceTokens

plugins {
    id 'java'
    id 'com.github.johnrengelman.shadow' version '8.1.1'
}

project.ext {
    ver = "1.4.4"
}

dependencies {
    implementation project(":common")
}

allprojects {
    apply plugin: 'java'

    base {
        archivesName = "Bingo"
    }
    version = ""

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(8)
        }
    }

    repositories {
        maven { url = "https://files.minecraftforge.net/maven" }
        maven {
            name = "AyStudio-Repository"
            url = "https://repo.mc9y.com/snapshots"
        }
        mavenLocal()
    }

    dependencies {
        compileOnly("org.projectlombok:lombok:1.18.30")
        annotationProcessor("org.projectlombok:lombok:1.18.30")
    }

    processResources {
        from(sourceSets.main.resources.srcDirs) {
            include '**/*.yml'
            filter ReplaceTokens, tokens: ["version": project.property("ver")]
            duplicatesStrategy DuplicatesStrategy.INCLUDE
        }
    }

    processResources {
        filteringCharset = "UTF-8"
    }

    tasks.withType(JavaCompile) {
        options.encoding = "UTF-8"
    }
}

subprojects.each { subproject -> evaluationDependsOn(subproject.path) }

tasks.register('allJar', Jar) {
    dependsOn subprojects.collect { it.tasks.named("build") }
    archiveBaseName = 'Bingo-' + project.property("ver")
    subprojects.each { subproject ->
        from subproject.tasks.named("jar").map { zipTree(it.outputs.files.singleFile) }
    }
}

tasks.jar.enabled = false

artifacts {
    archives allJar
}