title: "&8Common"
size: 27

# 当 ViewType 为 random 时, 才需要配置此参数, 并且 quest-item 配置失效, 改由 random-item 设定
viewType: default

# 每次查看都会计算条件, 语法与 group 条件语法一致
always-condition: [ ]

require-quests: &requreQuests [ "example1", "example2", "example3" ]
# 对 require-quests 数量匹配, 如果为 -1 则需要玩家有 requre-quests 全部任务才允许打开面板
# 这个参数一般用于配合 jobs 中类型为 random 的设定配合使用
require-count: -1

# repeat-quest-item 和 repeat-state-item 并非插件配置, 而是 YAML 语法, 只是方便利用重复的设定
repeat-quest-item: &questItem
  amount: 1
  data: 0
  # customModel: 0
  # nbt: "{}"
  name: "&f%questName%"
  lore:
    - ""
    - "%appendLore%"
    - " &f当前进度 %progress% &f(%pct%%) "
    - ""
repeat-state-item: &stateItem
  commands:
    - "say hahahahaha."
  state:
    - type: STAINED_GLASS_PANE
      amount: 1
      data: 13
      name: "&a已领取"
      lore: [ ]
    - type: STAINED_GLASS_PANE
      amount: 1
      data: 4
      name: "&e待领取"
      lore: [ ]
    - type: STAINED_GLASS_PANE
      amount: 1
      data: 14
      name: "&c未完成"
      lore: [ ]

#random-item:
#  # 显示的槽位
#  slots: [ 13,14,15 ]
#  item:
#    type: STONE
#    <<: *questItem

quest-item:
  - type: STONE
    <<: *questItem
    slot: 13
    quest: "example1"
  - type: DIRT
    <<: *questItem
    slot: 14
    quest: "example2"
  - type: SAND
    <<: *questItem
    slot: 15
    quest: "example3"

state-item:
  - slot: 12
    quests: *requreQuests
    claimKey: "default-1"
    <<: *stateItem
  - slot: 16
    quests: *requreQuests
    claimKey: "default-1"
    <<: *stateItem

items:
  - type: STAINED_GLASS_PANE
    amount: 1
    data: 15
    name: "&f"
    lore: [ ]
    slot: 0-9,17-26
  - type: IRON_INGOT
    amount: 1
    data: 0
    name: "&c▶ &aCommon"
    lore:
      - ""
      - "&e点击查看"
    slot: 10
    view: "default"
  - type: GOLD_INGOT
    amount: 1
    data: 0
    name: "&7Rare"
    lore:
      - ""
      - "&e点击查看"
    slot: 11
    view: "rare"