title: "&8Common"
size: 54

require-quests: &requreQuests [ "quest1", "quest2", "quest3" ]

# repeat-quest-item 与 repeat-state-item 非插件配置, 而是 YAML 语法, 只是方便利用重复的设定
repeat-quest-item: &questItem
  amount: 1
  data: 0
  # customModel: 0
  name: "&f%questName%"
  lore: [ ]
repeat-state-item: &stateItem
  state:
    - type: STAINED_GLASS_PANE
      amount: 1
      data: 14
      name: "&a已领取"
      lore: [ ]
    - type: STAINED_GLASS_PANE
      amount: 1
      data: 14
      name: "&e待领取"
      lore: [ ]
    - type: STAINED_GLASS_PANE
      amount: 1
      data: 14
      name: "&c未完成"
      lore: [ ]

quest-item:
  - type: STONE
    <<: *questItem
    slot: 13
    quest: "quest1"
  - type: STAINED_GLASS_PANE
    <<: *questItem
    slot: 14
    quest: "quest2"
  - type: STAINED_GLASS_PANE
    <<: *questItem
    slot: 15
    quest: "quest3"

state-item:
  1:
    slot: 12
    quests: *requreQuests
    <<: *stateItem
  2:
    slot: 16
    quests: *requreQuests
    <<: *stateItem

items:
  - type: STAINED_GLASS_PANE
    amount: 1
    data: 15
    name: "&f"
    lore: [ ]
    slot: 0-10,17-26