# 语言文件
language: zh_CN
# JavScriptEngine
script-engine: "JavaScript"
# 存储设定
data-option:
  # 存储类型, 支持: MySQL, SQLite, YAML
  type: YAML
  # MySQL url, 例如 jdbc:mysql://127.0.0.1/minecraft 格式: jdbc:mysql://MySQL地址/数据库名
  url: jdbc:mysql://localhost/minecraft?useSSL=false
  # 数据库用户名
  user: "root"
  # 数据库密码
  password: "root"
  # 数据库读取超时打开数据锁时长, 2 = 1秒
  time-out: 120
  # 同步提示
  pull-notify: true
# 任务进度条
progress:
  text: "::::::::::::::::::::"
  length: 20
  complete: "&a"
  undone: "&c"
# 是否开启任务触发输出
quest-trigger-log: false